### ISSUE TITLE
Specify list of files

### ISSUE THREAD

**Issue by vbraun** [pchudzik/angular-template-cache#3]
It would be nice to be able to pass a list of files instead of a file glob. Especially if some templates are autogenerated then you typically have a Makefile variable for that, and you don't want to glob over build artifacts. Right now it seems I have to do do a workaround like

```
nghtml2js --files "{$(shell echo $(HTML) | sed 's/ /,/g' )}" 
```

The commandline args would have to be slightly  different to support a variable-length list of files, e.g. `nghtml2s [options] file1 file2 ...`

**Comment by pchudzik** [comment]
file list can be provided after all options.
`nghtml2js -m 'reporter.template' -s es2015 -p src/ -o src/template.js -- src/file1.html src/file2.htm`
Please note that file list must be provided after -- (double dash)

It's possible to mix glob pattern and input file list
`nghtml2js -m 'reporter.template' -f html/**/*html -s es2015 -p src/ -o src/template.js -- index.html`

In case any of the input files is missing, or can not be read it's possible to ignore error by adding `--ignore-missing` option

New features are released in version 1.2.0
